spring:
  application:
    name: smartrecipe-backend
  
  # Database Configuration (Chạy trực tiếp ở local sẽ gọi vào port 3306 của Docker)
  datasource:
    url: jdbc:mysql://localhost:3306/smart_recipe_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: ${JWT_SECRET:U21hcnRSZWNpcGVfU3VwZXJTZWNyZXRLZXlfMjAyNl8xMjM0NTY3ODkw}
    expirationMs: ${JWT_EXPIRATION:86400000}
    refreshExpirationMs: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  port: 8080
